# Generated by Django 4.2.1 on 2023-06-04 05:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
