# Generated by Django 4.2.1 on 2023-06-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_log', '0002_alter_registro_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='confianza',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=9, verbose_name='Nivel de confianza'),
        ),
    ]
