# Generated by Django 4.2.1 on 2023-06-04 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_log', '0001_initial'),
        ('auth_stuff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rfid_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_log.tarjeta'),
        ),
    ]
